[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && pnpm install --filter @attestprotocol/horizon... && cd apps/horizon && pnpm prisma:generate && pnpm build"
watchPatterns = ["apps/horizon/**"]

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1
region = "us-west1"

[[services]]
name = "horizon-indexer"
icon = "🔭"

[[services.domains]]
domain = "${RAILWAY_PUBLIC_DOMAIN}"

[variables]
NODE_ENV = "production"
PORT = "${{PORT}}"
NODE_OPTIONS = "--max-old-space-size=1024"