[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && NODE_OPTIONS='--max-old-space-size=8192' pnpm install --ignore-scripts --filter @attestprotocol/horizon... && cd apps/horizon && pnpm run postinstall && NODE_OPTIONS='--max-old-space-size=8192' pnpm build"
watchPatterns = ["apps/horizon/**"]
nixpacksConfigPath = "apps/horizon/nixpacks.toml"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1
region = "us-west1"

[[services]]
name = "horizon-indexer"
icon = "🔭"

[[services.domains]]
domain = "${RAILWAY_PUBLIC_DOMAIN}"

[variables]
NODE_ENV = "production"
PORT = "${{PORT}}"
NODE_OPTIONS = "--max-old-space-size=1024"