# These keys are automatically generated by the stellar lab
# You can find them in the stellar lab account details
# https://lab.stellar.org/account/create

# the Attestation Protocol contract
export PROTOCOL_CONTRACT_ID="C..."
export AUTHORITY_RESOLVER_CONTRACT_ID="C..."

# Admin and token details
export ADMIN_SECRET_KEY="S..."
export ADMIN_ADDRESS="G..."

# The XLM token contract
export TOKEN_CONTRACT_ID="C..."

# User who will pay registration fee
export USER_SECRET_KEY="S..."
export USER_ADDRESS="G..."

# Authority details
export AUTHORITY_ADDRESS="G..."
export NEW_AUTHORITY_ADDRESS="G..."

# Attestation details
export ATTESTER_SECRET_KEY="S..."
export ATTESTER_ADDRESS="G..."
export RECIPIENT_ADDRESS="G..."