[package]
name = "protocol"
version = { workspace = true }
edition = "2021"
authors = ["Immutable Labs (Daccred) <gm@daccred.xyz>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
testutils = []

[dependencies]
soroban-sdk = { workspace = true }
stellar-xdr = { workspace = true, features = ["base64"] }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] } 
